== Binding specification v2

=== Main traits of Binding specification v2

==== Namespaces

YANG defines several namespaces and naming space of YANG is wider then applicable
namespace of JAVA language. In order to decrease conflicts between various
YANG-defined namespaces and classes introduced by Binding Specification, it
is needed to:

* separate namespaces by Java package hierarchy
** each namespace must define rules how to construct package name, which
   will not conflict with other namespace
* if multiple classes are generated for YANG statement they need to be in separate
  packages to decrease possible conflicts with siblings.
* if Binding Specification introduces new concepts, which does not have explicit
  namespace rules in YANG, these concepts needs to be in their own, separate
  namespaces, in order to not conflict on valid YANG namespace items.


This rules allows to identify two types of namespaces:

.Namespace types by source of namespace
YANG namespace::
  Naming space explicitly defined in YANG specification, which needs to be
  explicitly supported in order to prevent naming conflicts.
Binding namespace::
  Naming space introduced by Binding Specification for additional properties
  and functionality of Binding Specification. This namespaces needs to be separate
  from YANG namespaces in order to not have naming conflict with YANG-derived.


Binding Specification v2 uses following namespaces:

.Concrete namespaces used in Binding Specification
<<module-namespace>>::
  YANG namespace containing representation for all modules.
<<identity-namespace>>::
  YANG namespace containing representation for all `identity` statements. Identities
  needs to be separated to prevent naming conflict between Grouping, Data, Type
  namespaces.
<<type-namespace>>::
  YANG namespace containing representation for all `typedef` statements and
  annonymous definitions of `union`, `enumeration` and `bits` types. Types needs
  to be seperated to prevent naming conflict between Identity, Grouping and Data
  namespaces.
<<grouping-namespace>>::
  YANG namespace containing representation for all `grouping` statements and their
  child data node statements. Groupings needs to be separated to prevent naming
  conflict between Identity, Type, Data namespaces.
<<key-namespace>>::
  Binding namespace containing representation for all `key` statements.
  Representations of key statements needs to be in separate namespace, since it is not defined
  in YANG specification.
<<data-namespace>>::
  YANG namespace containing representation of instantiated data tree.
  Data needs to be separated to prevent naming conflict between Identity, Type,
  Grouping namespaces.
<<dto-namespace>>::
  Binding namespace containing Transfer Objects and Builders representing
  instantiated data tree items.

NOTE: Most of Binding Namespaces were introduced to decrease possibility of name
conflict between concepts defined in YANG and additional concepts introduced
by Binding Specification.

=== YANG Identifiers Mapping

Every non-Java char in identifier is converted to Java char by its unicode name http://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8
JAVA SE SPECIFICATIONS - Identifiers. This mapping solves various issues from Binding Specification v1, which led to compilation issues.

There are special types of mapping non-java chars to original identifiers according to specific Java type:

* class, enum, interface

** without special separator
the first character of identifier, any other first character of identifier part mapped by
** non-Java char name from unicode and char in identifier behind non-java char name are converting to upper case

 examples:
 example* - ExampleAsterisk
 example*example - ExampleAserisksExample
 \example - ReverseSolidusExample
 1example - DigitOneExample
 example1 - Example1
 int - IntReservedKeyword
 con - ConReservedKeyword

* enum value, constant
** used underscore as special separator
** converted identifier to upper case

 examples:
 example* - EXAMPLE_ASTERISK
 example*example - EXAMPLE_ASTERISK_EXAMPLE
 \example - REVERSE_SOLIDUS_EXAMPLE
 1example - DIGIT_ONE_EXAMPLE
 example1 - EXAMPLE1
 int - INT_RESERVED_KEYWORD
 con - CON_RESERVED_KEYWORD

* method, variable
** without special separator
** the first character of identifier is converting to lower case
** any other first character of identifier part mapped by non-Java char name from unicode and char in identifier behind non-java char name are converting to upper case

 examples:
 example* - exampleAsterisk
 example*example - exampleAserisksExample
 \example - reverseSolidusExample
 1example - digitOneExample
 example1 - example1
 int - intReservedKeyword
 con - conReservedKeyword

* package - full package name - https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
** parts of package name are separated by dots
** parts of package name are converting to lower case
** if parts of package name are reserved Java or Windows keywords, such as 'int' the suggested convention is to add an underscore to keyword
** dash is parsed as underscore according to https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

 examples:
 org.example* - org.exampleasterisk
 org.example*example - org.exampleasteriskexample
 org.example - org.reversesolidusexample
 org.1example - org.digitoneexample
 org.example1 - org.example1
 org.int - org.int_
 org.con - org.con_
 org.foo-cont - org.foo_cont

==== Special case - '-' in identifiers
There is special case in CLASS, INTERFACE, ENUM, ENUM VALUE, CONSTANT, METHOD and VARIABLE if
identifier contains single dash - then the converter ignores the single dash in the way of the
non-java chars. In other way, if dash is the first or the last char in the identifier or there is
more dashes in a row in the identifier, then these dashes are converted as non-java chars.

Example:

* class, enum, interface

 foo-cont - FooCont
 foo--cont - FooHyphenMinusHyphenMinusCont
 -foo - HyphenMinusFoo
 foo- - FooHyphenMinus

* enum value, constant

 foo-cont - FOO_CONT
 foo--cont - FOO_HYPHEN_MINUS_HYPHEN_MINUS_CONT
 -foo - HYPHEN_MINUS_FOO
 foo- - FOO_HYPHEN_MINUS

* method, variable

 foo-cont - fooCont
 foo--cont - fooHyphenMinusHyphenMinusCont
 -foo - hyphenMinusFoo
 foo- - fooHyphenMinus

==== Special case - same class (or enum or interface) names with different camel cases
Next special case talks about normalizing class name which already exists in package - but with
different camel cases (foo, Foo, fOo, ...). To every next classes with same names will by added
their actual rank (serial number), except the first one. This working for CLASS, ENUM and
INTEFACE java identifiers. If there exist the same ENUM VALUES in ENUM (with different camel
cases), then it's parsed with same logic like CLASSES, ENUMS and INTERFACES but according to list
of pairs of their ENUM parent. Example:

* class, enum, interface

 package name org.example, class (or interface or enum) Foo - normalized to Foo
 package name org.example, class (or interface or enum) fOo - normalized to Foo1

* enum value

 type enumeration {
     enum foo;
     enum Foo;
 }
 YANG enum values will be mapped to 'FOO' and 'FOO_1' Java enum values.

=== How to work with binding2-prototype-example